### ISSUE TITLE
Dataset annotations

### ISSUE THREAD

**Issue by oludash02** [hoangtv2000/UA_DETRAC_utils#1]
Hi,
Thanks for your great work! How did you go about downloading the annotations from the website? I have tried several times but the links do not work

**Comment by hoangtv2000** [comment]
Hi, 
In this work I downloaded and used the annotation from official website. But this website seems to be closed at the moment. So now you have to look up other website. For instance: https://d7.serctl.com/downloads1/2020-03-27-15-26-56-detrac-db.rit.albany.edu-DETRAC-Train-Annotations-XML-v3.zip

**Comment by oludash02** [comment]
Thanks! I was able to download it
